/*

 MAPOBJS.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : C:\Users\david\Desktop\gbtd22\SAVES\map.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define mapObjsWidth 20
#define mapObjsHeight 18
#define mapObjsBank 0

#define mapObjs mapObjsPLN0
extern unsigned char mapObjsPLN0[];

/* End of MAPOBJS.H */
